### PR TITLE
refactor: rename `ModelViewSet` class attr `model` to `model_class`

### PR DESCRIPTION
**Pull request by chengfangho**
#51 
Rename ModelViewSet class attr model to model_class

### CODE REVIEW

**Review by hbakri — CHANGES_REQUESTED** [review]
### Thank you for your contribution!

Firstly, let me express my sincerest gratitude for your time and efforts on this task. As an open-source project, we thrive on the contributions of volunteers like you, and I'm truly excited to see your involvement.

However, I've noticed that the changes proposed in this PR don't encompass all the occurrences where the `model` class attribute is used. This attribute has also been referred to in various examples and tests, and these references need to be updated as well to ensure consistency and avoid errors.

As a best practice for contributions, it's highly recommended to run the entire test suite before submitting a PR. This helps in identifying any potential issues that might arise from the proposed changes. In our case, you can use the command: 
```bash
export DJANGO_SETTINGS_MODULE=tests.test_settings
python -m poetry run coverage run -m django test
python -m poetry run coverage report
```
This will execute all the tests and then give you a detailed coverage.

Again, thank you so much for your contribution! Please don't hesitate to reach out if you need any assistance or have any questions. I look forward to your updated PR.

**Comment by chengfangho** [comment]
Hello,
Thank you so much for the feedback! I've run the tests and updated the PR. Let me know if there's anything else I missed.

**Review by hbakri — APPROVED** [review]
Hi @chengfangho,

Firstly, thank you again for the updates in this contribution! I appreciate it. You've done a great job!

I wanted to also let you know that I've run the tests workflow with your changes, and as you can see [here](https://github.com/hbakri/django-ninja-crud/actions/runs/5637644301) everything passed perfectly.

Regarding the changes in the README file, while it's always a good practice to keep the documentation up to date with the code changes, it's preferable in this case to leave the README unchanged until the new version is released. The reason for this is to avoid any confusion for users who might refer to the README for the current released version. However, it's not a problem at all, I'll handle reverting those changes on my side this time.

Going forward, we can keep this in mind for future contributions. Again, thank you for your hard work and understanding!

**Comment by chengfangho** [comment]
Thank you so much for taking the time to help me and provide feedback! I really appreciate your expertise in understanding the problems I was facing and I learned a lot from this.

**Comment by hbakri** [comment]
> Thank you so much for taking the time to help me and provide feedback! I really appreciate your expertise in understanding the problems I was facing and I learned a lot from this.

You're very welcome @chengfangho, and thank you for your kind words! It's a pleasure to see passionate contributors like you engaging with the project. Open source thrives on collaboration, and learning from each other is what makes it truly rewarding.

If you found our collaboration and the project valuable, please consider giving the repository a star 🌟 on GitHub. It's a simple way to support the project and helps us gain visibility within the community, allowing more people to benefit from our work.

Looking forward to future contributions, and feel free to reach out if you have any more questions or ideas. Happy coding!

**Pull request merged**
